In [9]:
import requests

url = "https://wuzzuf.net/api/search/job"

querystring = {"filter^\\[other^\\]^\\[slug^\\]":"=IT-Software-Development-Jobs-in-Egypt","page^\\[limit^\\]":"20","page^\\[offset^\\]":"1","filter[other][slug]":"=IT-Software-Development-Jobs-in-Egypt","page[limit]":"1","page[offset]":"0"}

payload = ""
headers = {
    "authority": "wuzzuf.net",
    "accept": "application/vnd.api+json",
    "accept-language": "en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6,af;q=0.5",
    "cookie": "_ga=GA1.2.1887984789.1642518415; __gads=ID=034401b27adf0086:T=1642518462:S=ALNI_Mbc5dbCoCZrf2lJCxFXDmwtfDskDw; _fbp=fb.1.1659374298462.481822549; _hjSessionUser_2811765=eyJpZCI6IjM0YjgxNTBhLWRmOTMtNWQwNC1iNzQ4LTg0ZWJhNzdlYWU3MiIsImNyZWF0ZWQiOjE2NTkzNzQyOTg5NjIsImV4aXN0aW5nIjp0cnVlfQ==; _gid=GA1.2.2079773432.1660826896; __gpi=UID=00000a6d84ba692d:T=1659374300:RT=1660826897:S=ALNI_MbN-7afk2zPDGGExCTsngogEAHJYg; _hjSession_2811765=eyJpZCI6IjgxMjc3MjQ4LTUzYjQtNGZmNi1hYmQzLWI1ODM2Mjg2YmE2OSIsImNyZWF0ZWQiOjE2NjA4MjY4OTc3NDcsImluU2FtcGxlIjpmYWxzZX0=; _hjAbsoluteSessionInProgress=1; ci_sessions=ehtbcpsaf4ig80icegam4r1ahbb4g16p; LiToken=feedcca6bf220d9ae3c4150f1f246c621660832443; __insp_wid=1101373123; __insp_nv=true; __insp_targlpu=aHR0cHM6Ly93dXp6dWYubmV0L2pvYnMvZWd5cHQ^%^3D; __insp_targlpt=Sm9icyBpbiBFZ3lwdCAtIFdVWlpVRiB8INmI2LjZgS7Zg9mI2YU^%^3D; __insp_identity=Z3Vlc3QtNWQyNjc4MTctMDY4OC00NTg2LWI1YzYtZDM3Njk5NGMyYzY5; __insp_norec_sess=true; __insp_slim=1660832453954; mp_f65e85d232fcb7d93f8de265b9818087_mixpanel=^%^7B^%^22distinct_id^%^22^%^3A^%^20^%^22182b1545664596-03cd53d876e0b9-26021d51-1fa400-182b1545665a15^%^22^%^2C^%^22^%^24device_id^%^22^%^3A^%^20^%^22182b1545664596-03cd53d876e0b9-26021d51-1fa400-182b1545665a15^%^22^%^2C^%^22^%^24initial_referrer^%^22^%^3A^%^20^%^22https^%^3A^%^2F^%^2Fwuzzuf.net^%^2Fjobs^%^2Fegypt^%^22^%^2C^%^22^%^24initial_referring_domain^%^22^%^3A^%^20^%^22wuzzuf.net^%^22^%^7D; cto_bundle=eet-al8wN1pkWEVXanJ0VndDd1V2JTJCMUl5TmpTRXRSckhqNWVESDZDSGExRXFJUk9iJTJCRmRZN3dYODd4ejVxVUhJSVBUeVdGZllNMG5oYURFT1ZwOHJxSjVmbUJmbk5BJTJGZWw5eGMzM3olMkJzcVhQc2tUaWNQb1FhSGslMkZhUG5kOEJrR1JtNFNaZk9ndGg0Z3lKVCUyRkk4VElIc1dpaEElM0QlM0Q",
    "referer": "https://wuzzuf.net/a/IT-Software-Development-Jobs-in-Egypt?start=0",
    "sec-ch-ua": "^\^Chromium^^;v=^\^104^^, ^\^"
}

r = requests.request("GET", url, data=payload, headers=headers, params=querystring)
job_number = r.json()
job_number = job_number["meta"].get("totalResultsCount")
print(job_number)

1439

In [10]:
import math
import requests
job_IDs = []
for i in range (math.ceil(job_number/1000)):
    url = "https://wuzzuf.net/api/search/job"

    querystring = {"filter^\\[other^\\]^\\[slug^\\]":"=IT-Software-Development-Jobs-in-Egypt","page^\\[limit^\\]":"20","page^\\[offset^\\]":"1","filter[other][slug]":"=IT-Software-Development-Jobs-in-Egypt","page[limit]":"1000","page[offset]":{i*1000}}

    payload = ""
    headers = {
        "authority": "wuzzuf.net",
        "accept": "application/vnd.api+json",
        "accept-language": "en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6,af;q=0.5",
        "cookie": "_ga=GA1.2.1887984789.1642518415; __gads=ID=034401b27adf0086:T=1642518462:S=ALNI_Mbc5dbCoCZrf2lJCxFXDmwtfDskDw; _fbp=fb.1.1659374298462.481822549; _hjSessionUser_2811765=eyJpZCI6IjM0YjgxNTBhLWRmOTMtNWQwNC1iNzQ4LTg0ZWJhNzdlYWU3MiIsImNyZWF0ZWQiOjE2NTkzNzQyOTg5NjIsImV4aXN0aW5nIjp0cnVlfQ==; _gid=GA1.2.2079773432.1660826896; __gpi=UID=00000a6d84ba692d:T=1659374300:RT=1660826897:S=ALNI_MbN-7afk2zPDGGExCTsngogEAHJYg; _hjSession_2811765=eyJpZCI6IjgxMjc3MjQ4LTUzYjQtNGZmNi1hYmQzLWI1ODM2Mjg2YmE2OSIsImNyZWF0ZWQiOjE2NjA4MjY4OTc3NDcsImluU2FtcGxlIjpmYWxzZX0=; _hjAbsoluteSessionInProgress=1; ci_sessions=ehtbcpsaf4ig80icegam4r1ahbb4g16p; LiToken=feedcca6bf220d9ae3c4150f1f246c621660832443; __insp_wid=1101373123; __insp_nv=true; __insp_targlpu=aHR0cHM6Ly93dXp6dWYubmV0L2pvYnMvZWd5cHQ^%^3D; __insp_targlpt=Sm9icyBpbiBFZ3lwdCAtIFdVWlpVRiB8INmI2LjZgS7Zg9mI2YU^%^3D; __insp_identity=Z3Vlc3QtNWQyNjc4MTctMDY4OC00NTg2LWI1YzYtZDM3Njk5NGMyYzY5; __insp_norec_sess=true; __insp_slim=1660832453954; mp_f65e85d232fcb7d93f8de265b9818087_mixpanel=^%^7B^%^22distinct_id^%^22^%^3A^%^20^%^22182b1545664596-03cd53d876e0b9-26021d51-1fa400-182b1545665a15^%^22^%^2C^%^22^%^24device_id^%^22^%^3A^%^20^%^22182b1545664596-03cd53d876e0b9-26021d51-1fa400-182b1545665a15^%^22^%^2C^%^22^%^24initial_referrer^%^22^%^3A^%^20^%^22https^%^3A^%^2F^%^2Fwuzzuf.net^%^2Fjobs^%^2Fegypt^%^22^%^2C^%^22^%^24initial_referring_domain^%^22^%^3A^%^20^%^22wuzzuf.net^%^22^%^7D; cto_bundle=eet-al8wN1pkWEVXanJ0VndDd1V2JTJCMUl5TmpTRXRSckhqNWVESDZDSGExRXFJUk9iJTJCRmRZN3dYODd4ejVxVUhJSVBUeVdGZllNMG5oYURFT1ZwOHJxSjVmbUJmbk5BJTJGZWw5eGMzM3olMkJzcVhQc2tUaWNQb1FhSGslMkZhUG5kOEJrR1JtNFNaZk9ndGg0Z3lKVCUyRkk4VElIc1dpaEElM0QlM0Q",
        "referer": "https://wuzzuf.net/a/IT-Software-Development-Jobs-in-Egypt?start=0",
        "sec-ch-ua": "^\^Chromium^^;v=^\^104^^, ^\^"
    }

    r = requests.request("GET", url, data=payload, headers=headers, params=querystring)


    data = r.json()

    for j in data['data']:
        job_IDs.append(j["id"])

    job_IDs_string = ",".join(job_IDs)

In [11]:
print(len(job_IDs))

1439

In [12]:

import pandas as pd
res = []

for i in range(0,len(job_IDs),100):
    job_IDs_string = ",".join(job_IDs[i:i+100])

    url = "https://wuzzuf.net/api/job?filter[other][ids]="+ job_IDs_string

    querystring = {"filter^\\[other^\\]^\\[ids^\\]": job_IDs_string}

    '''payload = ""
    headers = {
        "authority": "wuzzuf.net",
        "accept": "application/vnd.api+json",
        "accept-language": "en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6,af;q=0.5",
        "cookie": "_ga=GA1.2.1887984789.1642518415; __gads=ID=034401b27adf0086:T=1642518462:S=ALNI_Mbc5dbCoCZrf2lJCxFXDmwtfDskDw; _fbp=fb.1.1659374298462.481822549; _hjSessionUser_2811765=eyJpZCI6IjM0YjgxNTBhLWRmOTMtNWQwNC1iNzQ4LTg0ZWJhNzdlYWU3MiIsImNyZWF0ZWQiOjE2NTkzNzQyOTg5NjIsImV4aXN0aW5nIjp0cnVlfQ==; _gid=GA1.2.2079773432.1660826896; __gpi=UID=00000a6d84ba692d:T=1659374300:RT=1660826897:S=ALNI_MbN-7afk2zPDGGExCTsngogEAHJYg; _hjIncludedInSessionSample=0; _hjSession_2811765=eyJpZCI6IjgxMjc3MjQ4LTUzYjQtNGZmNi1hYmQzLWI1ODM2Mjg2YmE2OSIsImNyZWF0ZWQiOjE2NjA4MjY4OTc3NDcsImluU2FtcGxlIjpmYWxzZX0=; _hjAbsoluteSessionInProgress=1; ci_sessions=ehtbcpsaf4ig80icegam4r1ahbb4g16p; LiToken=b6bed86c553420d9b7c4aec65e0f43641660826906; __insp_wid=1101373123; __insp_slim=1660826910166; __insp_nv=true; __insp_targlpu=aHR0cHM6Ly93dXp6dWYubmV0L2pvYnMvZWd5cHQ^%^3D; __insp_targlpt=Sm9icyBpbiBFZ3lwdCAtIFdVWlpVRiB8INmI2LjZgS7Zg9mI2YU^%^3D; __insp_identity=Z3Vlc3QtNWQyNjc4MTctMDY4OC00NTg2LWI1YzYtZDM3Njk5NGMyYzY5; __insp_norec_sess=true; _gat=1; mp_f65e85d232fcb7d93f8de265b9818087_mixpanel=^%^7B^%^22distinct_id^%^22^%^3A^%^20^%^22182b0ffa2df1ba-0cdd4929f13d8e-26021d51-1fa400-182b0ffa2e0153^%^22^%^2C^%^22^%^24device_id^%^22^%^3A^%^20^%^22182b0ffa2df1ba-0cdd4929f13d8e-26021d51-1fa400-182b0ffa2e0153^%^22^%^2C^%^22^%^24initial_referrer^%^22^%^3A^%^20^%^22https^%^3A^%^2F^%^2Fwuzzuf.net^%^2Fjobs^%^2Fegypt^%^22^%^2C^%^22^%^24initial_referring_domain^%^22^%^3A^%^20^%^22wuzzuf.net^%^22^%^7D; cto_bundle=cBvTYF8wN1pkWEVXanJ0VndDd1V2JTJCMUl5Tmx6YlFWbWpxbUdBbEJaM0ZiU2dZNVU1Qm5RVVVBeHp2TlB4YWJmNVpxTFhOQUZZTVhLWWhpUU53Ym1WJTJCSjM4VGdoJTJCMjhSUWlOOHJ3OSUyQkQyZWZJUnl6VkNJb0xpNEdXaWNHMVBIN09waEp1VEw2dE5ZVVlvNG1sd1lkTm5leWJ1ZyUzRCUzRA",
        "referer": "https://wuzzuf.net/a/IT-Software-Development-Jobs-in-Egypt?ref=browse-jobs&start=20",
        "sec-ch-ua": "^\^Chromium^^;v=^\^104^^, ^\^"
    }'''

    r = requests.request("GET", url, data=payload, headers=headers, params=querystring)

    data = r.json()
    for j in data["data"]:
        res.append(j)

In [13]:
print (len(res))

1439

In [14]:
df = pd.json_normalize(res)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1439 entries, 0 to 1438
Data columns (total 67 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   type                                                        1439 non-null   object
 1   id                                                          1439 non-null   object
 2   attributes.jobType                                          1439 non-null   object
 3   attributes.applicationType                                  1439 non-null   object
 4   attributes.status                                           1439 non-null   object
 5   attributes.title                                            1439 non-null   object
 6   attributes.description                                      1439 non-null   object
 7   attributes.requirements                                     1432 non-null   object
 8   attributes.salary.min                                       133 non-null    float64
 9   attributes.salary.max                                       133 non-null    float64
 10  attributes.salary.currency                                  0 non-null      float64
 11  attributes.salary.period                                    0 non-null      float64
 12  attributes.salary.additionalDetails                         186 non-null    object
 13  attributes.salary.isPaid                                    1439 non-null   bool
 14  attributes.keywords                                         1439 non-null   object
 15  attributes.careerLevel.id                                   1439 non-null   int64
 16  attributes.careerLevel.name                                 1439 non-null   object
 17  attributes.careerLevel.hint                                 1329 non-null   object
 18  attributes.careerLevel.browsePage                           1439 non-null   object
 19  attributes.location.country.id                              1439 non-null   int64
 20  attributes.location.country.name                            1439 non-null   object
 21  attributes.location.country.code                            1439 non-null   object
 22  attributes.location.city.id                                 1439 non-null   int64
 23  attributes.location.city.name                               1439 non-null   object
 24  attributes.location.city.latitude                           1439 non-null   object
 25  attributes.location.city.longitude                          1439 non-null   object
 26  attributes.location.area.id                                 1081 non-null   float64
 27  attributes.location.area.name                               1081 non-null   object
 28  attributes.location.area.latitude                           1081 non-null   object
 29  attributes.location.area.longitude                          1081 non-null   object
 30  attributes.workExperienceYears.min                          1379 non-null   float64
 31  attributes.workExperienceYears.max                          1147 non-null   float64
 32  attributes.vacancies                                        1439 non-null   int64
 33  attributes.workRoles                                        1439 non-null   object
 34  attributes.workTypes                                        1439 non-null   object
 35  attributes.schools                                          1439 non-null   object
 36  attributes.candidatePreferences.gender                      50 non-null     object
 37  attributes.candidatePreferences.educationLevel.id           1439 non-null   int64
 38  attributes.candidatePreferences.educationLevel.name         1439 non-null   object
 39  attributes.candidatePreferences.requiresBachelorDegree      1439 non-null   bool
 40  attributes.candidatePreferences.requiresGoodProfileMeter    1439 non-null   bool
 41  attributes.candidatePreferences.requiresAcademicExcellence  1439 non-null   bool
 42  attributes.hotScore                                         1439 non-null   int64
 43  attributes.logo                                             0 non-null      object
 44  attributes.slug                                             1439 non-null   object
 45  attributes.uri                                              1439 non-null   object
 46  attributes.views                                            1439 non-null   int64
 47  attributes.redirectUrl                                      0 non-null      object
 48  attributes.tempWorkingFromHome                              1439 non-null   bool
 49  attributes.hideCompany                                      1439 non-null   bool
 50  attributes.hideGender                                       1439 non-null   bool
 51  attributes.hideSalary                                       1439 non-null   bool
 52  attributes.settings.isAutoPosted                            38 non-null     object
 53  attributes.settings.isHighlighted                           2 non-null      object
 54  attributes.settings.isFeatured                              46 non-null     object
 55  attributes.postedAt                                         1439 non-null   object
 56  attributes.expireAt                                         1439 non-null   object
 57  relationships.company.data                                  0 non-null      float64
 58  links.self                                                  1439 non-null   object
 59  relationships.company.data.type                             1290 non-null   object
 60  relationships.company.data.id                               1290 non-null   object
 61  attributes.location.area                                    0 non-null      float64
 62  attributes.salary.currency.id                               133 non-null    float64
 63  attributes.salary.currency.name                             133 non-null    object
 64  attributes.salary.currency.code                             133 non-null    object
 65  attributes.salary.period.id                                 133 non-null    float64
 66  attributes.salary.period.name                               133 non-null    object
dtypes: bool(8), float64(11), int64(7), object(41)
memory usage: 674.7+ KB

In [16]:
df.columns = df.columns.str.replace('attributes', '')
df.columns = df.columns.str.replace('.', ' ')
df.columns = df.columns.str.strip()

C:\Users\Basel\AppData\Local\Temp\ipykernel_12004\1777131512.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df.columns = df.columns.str.replace('.', ' ')

In [17]:
df['keywords'][0]

[{'name': 'Computer Science',
  'browsePage': 'a/Computer-Science-Jobs-in-Egypt'},
 {'name': 'developer', 'browsePage': 'a/Developer-Jobs-in-Egypt'},
 {'name': 'Front end', 'browsePage': 'a/Front-End-Jobs-in-Egypt'},
 {'name': 'JavaScript', 'browsePage': 'a/JavaScript-Jobs-in-Egypt'},
 {'name': 'mobile application',
  'browsePage': 'a/Mobile-Application-Jobs-in-Egypt'}]

In [18]:
import re

def useRegex(input):
    pattern = re.compile(r"'[^']*'", re.IGNORECASE)
    return re.search(pattern,input).group()

In [19]:
for i in range(len(df)):
    keywords_string = df["keywords"][i]
    keywords_array = []
    for x in keywords_string:
        keywords_array.append(useRegex(str(x.values())))

    new_keywords_string = ','.join(keywords_array)
    df["keywords"][i] = new_keywords_string

C:\Users\Basel\AppData\Local\Temp\ipykernel_12004\2697081002.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["keywords"][i] = new_keywords_string

In [20]:
df["keywords"]

0       'Computer Science','developer','Front end','Ja...
1       'engineer','Software Development','Software En...
2       'Quality Assurance','Certified Software Tester...
3       'Computer Science','Information Technology (IT...
4       '.Net Framework','C#','ASP.Net Web API','OOP',...
                              ...
1434    'Analysis','analytical','Business Analysis','C...
1435    'Software Development','Computer Science','Sof...
1436    'flutter','Flutter developer','Software Develo...
1437    '.Net','API','DevExpress','SQL Server','NET','...
1438    'Agile','API','Computer Science','Design','Dev...
Name: keywords, Length: 1439, dtype: object

In [21]:
df

,type,id,jobType,applicationType,status,title,description,requirements,salary min,salary max,...,relationships company data,links self,relationships company data type,relationships company data id,location area,salary currency id,salary currency name,salary currency code,salary period id,salary period name
0,job,f885f910-ed0d-4667-921d-e059313683e1,job,internal,active,Senior front end developer mobile application,<p>We're in need of a talented senior Front-En...,<ul><li></li></ul>,NaN,NaN,...,NaN,https://wuzzuf.net/api/job/f885f910-ed0d-4667-...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,job,2a133a52-5d22-4557-b1a8-214b485390a7,job,internal,active,Senior Software Engineer (PHP),<ul><li>Produce detailed specifications</li><l...,<ul><li>Bachelor of Computer Science or Engine...,NaN,NaN,...,NaN,https://wuzzuf.net/api/job/2a133a52-5d22-4557-...,company,16621,NaN,NaN,NaN,NaN,NaN,NaN
2,job,b0136a5f-b36d-4ca1-8f34-6fd524819414,job,internal,active,Software Quality Control Engineer,<p><br>We are looking for a Quality Control (Q...,"<ul><li>Review requirements, specifications an...",NaN,NaN,...,NaN,https://wuzzuf.net/api/job/b0136a5f-b36d-4ca1-...,company,20425,NaN,NaN,NaN,NaN,NaN,NaN
3,job,b3ab10b7-4a17-49a9-a99f-1a25604ab9f1,job,internal,active,Software Quality Engineer,"<ul><li>Create, review and execute automated /...",<ul><li>3-5 Years Of Experience.</li><li>Famil...,NaN,NaN,...,NaN,https://wuzzuf.net/api/job/b3ab10b7-4a17-49a9-...,company,27241,NaN,NaN,NaN,NaN,NaN,NaN
4,job,bc0a5a86-a80a-4486-83ab-0ca48b2146fd,job,internal,active,Senior Product Customer Support Engineer,<p>For a reputable software company in Educati...,<p><strong>Qualifications</strong></p><ul><li>...,NaN,NaN,...,NaN,https://wuzzuf.net/api/job/bc0a5a86-a80a-4486-...,company,22617,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1434,job,b38fe311-47fa-4eb2-be16-1099710b3e98,job,internal,active,Business Analyst,<ul><li>Turn 'business strategy' into 'optimiz...,<ul><li>Data analysis and formulating resultin...,NaN,NaN,...,NaN,https://wuzzuf.net/api/job/b38fe311-47fa-4eb2-...,company,35020,NaN,NaN,NaN,NaN,NaN,NaN
1435,job,8bd3df44-56ff-430f-916b-75e4e9e746a9,job,internal,active,Imaging DotNet Developer,<p>MILLENSYS is now Hiring to join our team<st...,<p>Education<br>----------<br>Only Computer En...,NaN,NaN,...,NaN,https://wuzzuf.net/api/job/8bd3df44-56ff-430f-...,company,17673,NaN,NaN,NaN,NaN,NaN,NaN
1436,job,5adf8f76-c34d-4338-8c43-d3d1063693d0,job,internal,active,Flutter Developer,"<p>Develop new features, troubleshoot, and fix...",<p>Have more than 1 year of experience with Fl...,NaN,NaN,...,NaN,https://wuzzuf.net/api/job/5adf8f76-c34d-4338-...,company,8875,NaN,NaN,NaN,NaN,NaN,NaN
1437,job,3c8208e7-bbc2-4ae4-9c88-30cfb351bd7b,job,internal,active,Full Stack Developer C#.net -desktop,<ul><li>Responsible to create an Application a...,"<ul><li>VS 2019, C#.net , SQL Server.</li><li>...",NaN,NaN,...,NaN,https://wuzzuf.net/api/job/3c8208e7-bbc2-4ae4-...,company,8875,NaN,NaN,NaN,NaN,NaN,NaN
1438,job,e9d8d809-fe13-414e-80e8-8e24da4a31f4,job,internal,active,Odoo Developer,<ul><li>Develop and customize Odoo modules as ...,<ul><li>Bachelor’s degree in Computer Science ...,NaN,NaN,...,NaN,https://wuzzuf.net/api/job/e9d8d809-fe13-414e-...,company,11587,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
import os
# if file does not exist write header 
if not os.path.isfile('wuzzuf_IT_jobs 08-11-2022.csv'):
   df.to_csv('wuzzuf_IT_jobs 24-02-2022.csv', header='column_names')
else: # else it exists so append without writing the header
   df.to_csv('wuzzuf_IT_jobs 24-02-2022.csv', mode='a', header=False)

c:\Users\Basel\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\internals\blocks.py:2323: RuntimeWarning: invalid value encountered in cast
  values = values.astype(str)

In [23]:
df_summary = df[['title','description']]

In [24]:
df_summary.head()

,title,description
0,Senior front end developer mobile application,<p>We're in need of a talented senior Front-En...
1,Senior Software Engineer (PHP),<ul><li>Produce detailed specifications</li><l...
2,Software Quality Control Engineer,<p><br>We are looking for a Quality Control (Q...
3,Software Quality Engineer,"<ul><li>Create, review and execute automated /..."
4,Senior Product Customer Support Engineer,<p>For a reputable software company in Educati...

In [25]:
from bs4 import BeautifulSoup

for i in range(len(df_summary)):
    html = df_summary['description'][i]
    soup = BeautifulSoup(html)
    df_summary['description'][i] = soup.get_text()

C:\Users\Basel\AppData\Local\Temp\ipykernel_12004\529813701.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_summary['description'][i] = soup.get_text()

In [26]:
df_summary.head()

,title,description
0,Senior front end developer mobile application,We're in need of a talented senior Front-End D...
1,Senior Software Engineer (PHP),"Produce detailed specificationsWrite “clean”, ..."
2,Software Quality Control Engineer,We are looking for a Quality Control (QC) engi...
3,Software Quality Engineer,"Create, review and execute automated / manual ..."
4,Senior Product Customer Support Engineer,"For a reputable software company in Education,..."

In [27]:
df = df.iloc[df.astype(str).drop_duplicates().index]
df.shape

(1439, 67)